### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by SidShaytay** [johndatserakis/koa-react-notes-web#1]
Pretty basic ... current [master](https://github.com/johndatserakis/koa-react-notes-web/commit/88a850cdce56ea0878c73de93d2a52bb2b75f7dd) doesn't build on Windows or Mac.

## Steps

1. `git clone <this repo>`
2. `npm install` 
3. `npm run watch`

## Result

```
Failed to compile

./src/index.js
Module not found: Can't resolve 'App' in 'D:\temp\koa-react-notes-web\src'

This error occurred during the build time and cannot be dismissed.
```

## Versions / Env
```
node --version
v8.10.0

npm --version
5.6.0
```

Windows 10 x64 v1803 as well as macOS 10.13.5.

**Comment by SidShaytay** [comment]
Also, good stuff. Wanted to check out the authentication pieces in closer detail by pointing this to your live backend.

**Comment by johndatserakis** [comment]
What an interesting issue.

I hadn't opened the project in about a week or two. RIght now, because of your issue, I deleted my node_modules and package-lock.json, ran npm i and then npm run watch.

I then got a similar error message to the one you're getting. I had never seen it before. It mentioned something about not being able access `status` of something that was undefined. I think I have an idea of what that may be. After a few refreshes, I decided to launch the [backend api](https://github.com/johndatserakis/koa-vue-notes-api) for the project to see if that would fix the error - so I ran npm run watch in that (I already have it npm installed).

As soon as I did that, the issue went away. And what's even stranger - I can't get it to come back! I've stopped the backend, npm installed again, deleted the node_modules and package-lock.json, restarted my computer, cleared my browser's cache, tried other browsers... nothing gets the message back! 

So I'm going to continue looking to make this error show so I can fix the undefined accessing of the variable. Sorry about this. It seems like somethings cached in my computer once it accesses the api - very strange. Good catch.

**Comment by johndatserakis** [comment]
Um - sorry I forgot to ask something super simple - have you set your `.env` files like I mentioned in the `readme`? I have a feeling that's what you're missing - it's messing with your imports. Let me know!

**Comment by SidShaytay** [comment]
I’m out for a week but no - only what’s mentioned in the “Installing / Getting started” section. I think any mandatory step should be listed there.

**Comment by johndatserakis** [comment]
Yea it's listed a paragraph down `When cloning the project you'll want to take each .env file and remove .example from it. This is where I set a few environmental variables for the project's use. Some highlights are NODE_PATH=src in the .env file - that let's you easily import files from anywhere in your app using src as the root.`

Maybe the note should be moved higher up. I'm sure following those steps will solve your problem.

**Comment by johndatserakis** [comment]
Hey - did you get this going?

**Comment by SidShaytay** [comment]
@johndatserakis yup, that at least runs. Thanks. IMHO, if everyone *must* perform that step to make it functional, that ought to be reflected in the state of the repo itself.

**Comment by johndatserakis** [comment]
I hear you - it’s just that the .env files are all gitignored- it’s because that’s where you store sensitive information for your app. What I can do though is make it more clear that you have to adjust the example .env’s, so that people don’t have trouble running the project from the beginning.

Thanks for your help.
