### ISSUE TITLE
Love this! One question

### ISSUE THREAD

**Issue by notflip** [johndatserakis/koa-react-notes-web#2]
I'm learning about the axios interceptor and how to handle 401's from the API.

In your example I see all this code is in the UserActions. Is this good practice? Just wondering why it's placed in the UserActions.js. 

Thank you for this repo!

**Comment by johndatserakis** [comment]
Thanks for checking it out!

Ah yes, the interceptors. Well, these axios interceptors are actually some of the most difficult and complicated parts of the program (Although once they're set up you really don't have to worry about them). This is due to the fact that they have to automatically catch very specific errors from the API and **resend** the same call the caused the initial errors but with an updated user auth token.

The steps are:
- User is logged in and has an auth token. They go to make a protected API call but their auth token is expired.
- Because the auth token is expired, the backend sends a very specific response back, with the status set to 401 and the message as `TOKEN_EXPIRED`.
- Using the interceptor, axios identifies that this API called failed because of this very specific reason, so - while we're still in the middle of the call (but in a sort of paused state), axios goes and refreshes the user's token using a different endpoint, and then saves the result.
- *Then*, axios takes the initial call that failed (that it saved), and resubmits it - but with the new token.

You see, all this is done, automatically, without the user ever hearing about any of this. This is made possible because of these interceptors, and because axios uses promises and we don't break the promise chain during all of this.

I use similar code in the Vue sister of this project [here](https://github.com/johndatserakis/koa-vue-notes-web/blob/master/src/store/user.js). You'll find this pattern is very common in production apps - but it was hard to find a real example of this - that's one of the main reasons I made these projects open-source.

Now, as to why I put them in the userActions.js - I mainly do this because they only need to be registered once - and the userActions (whether in Vue or React) is sort of like the brain of the operation when there is user login functionality. I find that this works well in my uses. One thing to note is that when logging out you need to send a logout action to each module - so that each module cleans up its own data - just a small note.

As far as handling 401's - you'd just do that normally in you actual API calls - those won't be stopped unless they also send the `TOKEN_EXPIRED` message, which they wouldn't of course.

**Comment by notflip** [comment]
Thanks so much for your explanation! I'm learning so much from this repo.
Like you said there's so few well implemented JWT examples online! Thank for making this open source.

**Comment by johndatserakis** [comment]
Very welcome - glad the project can help!
