### ISSUE TITLE
Why is a new async function returned here?

### ISSUE THREAD

**Issue by notflip** [johndatserakis/koa-react-notes-web#3]
https://github.com/johndatserakis/koa-react-notes-web/blob/68d7b65d56c31736918a6cad2d21b1428846eb79/src/store/actions/userActions.js#L121

Just trying to understand your code! Thanks

**Comment by johndatserakis** [comment]
Good question - the reason you see the `async` keyword there is because in the accompanying function I am using `await` to wait for a Promise. This is the pattern for the new [async/await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) functionality proposed in JavaScript. Before, Promises had to be dealt with by using the `.then()` syntax, but with `async/await` you can avoid a lot of the callback trouble that causes.

All my Redux actions return Promises so that when they're called in components or wherever I can call them as Promises - see something like [here](https://github.com/johndatserakis/koa-react-notes-web/blob/68d7b65d56c31736918a6cad2d21b1428846eb79/src/components/Program/CreateNote.js#L37) where I dispatch the `create` note action when a user creates a note.
